[workspace]
authors = ["Akulen <tomas@rigaux.com>"]
channels = ["conda-forge"]
name = "MTGateau"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
matplotlib = ">=3.10.6,<4"
equinox = ">=0.13.0,<0.14"
pytorch-gpu = "*"
beartype = ">=0.21.0,<0.22"
polars = ">=1.33.1,<2"
requests = ">=2.32.5,<3"
optax = ">=0.2.6,<0.3"
aim = ">=3.27.0,<4"
jax = ">=0.7.1,<0.8"
jaxlib = { version = "*", build = "*cuda*" }
ipython = ">=9.5.0,<10"
pynvim = ">=0.6.0,<0.7"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.9,<5"
pillow = ">=11.3.0,<12"
humanfriendly = ">=10.0,<11"

[pypi-dependencies]
humanhash3 = ">=0.0.6, <0.0.7"
transformers = { git = "https://github.com/huggingface/transformers", rev = "v4.56.0-Embedding-Gemma-preview" }
sentence-transformers = ">=5.1.1, <6"
pyarrow = ">=21.0.0, <22"
